image:
  name: "huertalv/product-service"
  tag: "1.0.0"


resources:
  limits:
    cpu: 1
    memory: 700Mi
  requests:
    cpu: 100m
    memory: 500Mi

hpa:
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 100

host: product-app-testing
port: 8080