apiVersion: v1
kind: Service
metadata:
  name: {{ template "product-service.name" . }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    name: {{ .Release.Name }}
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}